<?php
require __DIR__.'/bootstrap.php';
$checks=0;
function check($condition,$message){global $checks;if(!$condition){throw new Exception('FAILED: '.$message);}++$checks;}
function rejects($fn,$message){$rejected=false;try{$fn();}catch(RuntimeException $e){$rejected=true;}check($rejected,$message);}
$order=$GLOBALS['orders'][300];
JPD_OD_Jobs::cleanup(true);
try {
    check(JPD_OD_Plugin::actor()===0,'customer does not gain staff role');
    check(!JPD_OD_Plugin::allowed($order),'customer owner cannot send');
    user_switching::$old=new WP_User(7);
    check(JPD_OD_Plugin::actor()===0,'old user cookie alone is insufficient');
    user_switching::$auth=true;
    check(JPD_OD_Plugin::actor()===7,'verified original staff recognized');
    check(JPD_OD_Plugin::allowed($order),'switched staff can send own customer order');
    $other=clone $order;$other->customer=50;
    check(!JPD_OD_Plugin::allowed($other),'switched seller cannot access another customer order');
    user_switching::$old->staff=false;
    check(JPD_OD_Plugin::actor()===0,'unprivileged original user refused');
    $GLOBALS['staff']=true;
    check(JPD_OD_Plugin::allowed($other),'direct manager can access orders');
    $GLOBALS['staff']=false;user_switching::$old=new WP_User(7);
    $GLOBALS['uid']=0;check(JPD_OD_Plugin::actor()===0,'switched cookie without logged-in session refused');$GLOBALS['uid']=12;
    $_SERVER['REQUEST_METHOD']='POST';$_POST=array('order'=>300,'command'=>'start','nonce'=>'wrong','formats'=>'["csv"]');
    try{JPD_OD_Plugin::ajax();}catch(JsonReply $e){check(!$e->success&&$e->status===403,'AJAX rejects bad nonce');}
    $_POST['nonce']=wp_create_nonce('jpd_od_300');user_switching::$auth=false;
    try{JPD_OD_Plugin::ajax();}catch(JsonReply $e){check(!$e->success&&$e->status===403,'AJAX rejects expired switching auth');}user_switching::$auth=true;
    $data=JPD_OD_Documents::collect($order);
    check($data['qty']===3.0&&$data['total']===37.5,'current product price, order quantity');
    $GLOBALS['products'][101]->price='14';$fresh=JPD_OD_Documents::collect($order);
    check($fresh['total']===42.0,'new collection reflects new price');
    $GLOBALS['products'][101]->price='';$fallback=JPD_OD_Documents::collect($order);
    check($fallback['total']===30.0&&$fallback['rows'][0]['source']==='Αποθηκευμένη αξία γραμμής','missing price uses saved line total');
    unset($GLOBALS['products'][101]);$missing=JPD_OD_Documents::collect($order);
    check(count($missing['rows'])===1&&$missing['warnings']===1,'missing product retained with warning');
    $GLOBALS['products'][101]=new WC_Product(101);
    $GLOBALS['exclude']=1;check(!JPD_OD_Documents::collect($order)['rows'],'existing exclusion filter respected');unset($GLOBALS['exclude']);
    rejects(fn()=>JPD_OD_Jobs::start($order,7,array('print')),'photo format refused');
    rejects(fn()=>JPD_OD_Jobs::start($order,7,array('csv','csv')),'duplicate formats refused');
    rejects(fn()=>JPD_OD_Jobs::start($order,7,array(array('csv'))),'nested malformed format refused without PHP warnings');
    rejects(fn()=>JPD_OD_Jobs::start($order,7,array()),'empty formats refused');
    $order->email='bad';rejects(fn()=>JPD_OD_Jobs::start($order,7,array('csv')),'invalid billing email refused');$order->email='customer@example.test';
    $job=JPD_OD_Jobs::start($order,7,array('csv'));$token=$job['token'];$dir=JPD_OD_Jobs::root().'/'.$token;
    check(is_dir($dir)&&strpos(realpath($dir),realpath(dirname(ABSPATH)))!==0,'documents outside website');
    rejects(fn()=>JPD_OD_Jobs::run('../escape',$order,7,'status'),'traversal token refused');
    rejects(fn()=>JPD_OD_Jobs::run($token,$order,8,'status'),'different seller refused');
    $GLOBALS['session']='other';rejects(fn()=>JPD_OD_Jobs::run($token,$order,7,'status'),'different WP session refused');$GLOBALS['session']='tablet-session';
    $GLOBALS['blog']=2;rejects(fn()=>JPD_OD_Jobs::run($token,$order,7,'status'),'different multisite site refused');$GLOBALS['blog']=1;
    $GLOBALS['uid']=50;rejects(fn()=>JPD_OD_Jobs::run($token,$order,7,'status'),'different current user refused');$GLOBALS['uid']=12;
    rejects(fn()=>JPD_OD_Jobs::run($token,$order,7,'send'),'incomplete job cannot send');check(WC_Email::$count===0,'no mail before documents ready');
    $GLOBALS['products'][101]->price='19';
    $ready=JPD_OD_Jobs::run($token,$order,7,'generate','csv');
    check($ready['canSend']&&$ready['status']==='ready','CSV generated before send');
    $csv=file_get_contents($dir.'/'.$ready['files'][0]['name']);
    check(substr($csv,0,3)==="\xEF\xBB\xBF"&&strpos($csv,'12,5000')!==false,'UTF8 BOM and frozen live collection consistent');
    check(JPD_OD_Collector::csv_text('=HYPERLINK("bad")')[0]==="'",'spreadsheet text formula neutralized');
    $twice=JPD_OD_Jobs::run($token,$order,7,'generate','csv');check($ready['files']===$twice['files'],'generation retry reuses same operation file');
    $state=json_decode(file_get_contents($dir.'/state.json'),true);check(!isset($state['data']),'ready receipt removes product snapshot');
    $GLOBALS['limit']=1024;file_put_contents($dir.'/'.$ready['files'][0]['name'],str_repeat('a',2048));
    $state['files']['csv']['bytes']=2048;$state['files']['csv']['sha256']=hash_file('sha256',$dir.'/'.$ready['files'][0]['name']);JPD_OD_Jobs::write($dir,$state);
    rejects(fn()=>JPD_OD_Jobs::run($token,$order,7,'send'),'attachment size guard server-side');check(WC_Email::$count===0,'no partial email for oversize files');$GLOBALS['limit']=20*1024*1024;
    file_put_contents($dir.'/'.$ready['files'][0]['name'],$csv);$state['files']['csv']['bytes']=strlen($csv);$state['files']['csv']['sha256']=hash('sha256',$csv);JPD_OD_Jobs::write($dir,$state);
    $lock=fopen($dir.'/operation.lock','c');flock($lock,LOCK_EX);
    rejects(fn()=>JPD_OD_Jobs::run($token,$order,7,'send'),'concurrent request refused');flock($lock,LOCK_UN);fclose($lock);
    $sent=JPD_OD_Jobs::run($token,$order,7,'send');
    check($sent['status']==='sent'&&WC_Email::$count===1,'one native manual email');
    check(WC_Email::$captured['to']===$order->email&&count(WC_Email::$captured['attachments'])===1,'billing email and selected file only');
    check(strpos(WC_Email::$captured['body'],'my-account/orders/')!==false&&strpos(WC_Email::$captured['body'],'Πουκάμισο')===false,'simple email body with orders link');
    check(!glob($dir.'/*.csv')&&!glob($dir.'/*.pdf'),'attachments deleted after dispatch');
    JPD_OD_Jobs::run($token,$order,7,'send');check(WC_Email::$count===1,'duplicate send uses receipt, no new email');
    check(count($order->notes)===1,'successful acceptance noted once');
    $new=JPD_OD_Jobs::start($order,7,array('csv'));$newDir=JPD_OD_Jobs::root().'/'.$new['token'];$snapshot=json_decode(file_get_contents($newDir.'/state.json'),true);
    check((float)$snapshot['data']['total']===57.0,'new operation uses fresh current price');
    JPD_OD_Jobs::run($new['token'],$order,7,'generate','csv');$order->items[1]->qty=4;
    rejects(fn()=>JPD_OD_Jobs::run($new['token'],$order,7,'send'),'changed quantities block old documents');check(!glob($newDir.'/*.csv'),'changed-order files discarded');$order->items[1]->qty=3;
    $failed=JPD_OD_Jobs::start($order,7,array('csv'));JPD_OD_Jobs::run($failed['token'],$order,7,'generate','csv');WC_Email::$result=false;
    check(JPD_OD_Jobs::run($failed['token'],$order,7,'send')['status']==='failed','mail false surfaced as failure');
    rejects(fn()=>JPD_OD_Jobs::run($failed['token'],$order,7,'send'),'failed dispatch cannot be blindly retried');WC_Email::$result=true;
    $uncertain=JPD_OD_Jobs::start($order,7,array('csv'));JPD_OD_Jobs::run($uncertain['token'],$order,7,'generate','csv');WC_Email::$throw=true;
    check(JPD_OD_Jobs::run($uncertain['token'],$order,7,'send')['status']==='uncertain','SMTP exception surfaced as uncertain');WC_Email::$throw=false;
    $n=WC_Email::$count;rejects(fn()=>JPD_OD_Jobs::run($uncertain['token'],$order,7,'send'),'uncertain dispatch not repeated');check(WC_Email::$count===$n,'no duplicate after uncertain result');
    $orphan=JPD_OD_Jobs::start($order,7,array('csv'));JPD_OD_Jobs::run($orphan['token'],$order,7,'generate','csv');$orphanDir=JPD_OD_Jobs::root().'/'.$orphan['token'];$s=json_decode(file_get_contents($orphanDir.'/state.json'),true);$s['status']='sending';JPD_OD_Jobs::write($orphanDir,$s);
    check(JPD_OD_Jobs::run($orphan['token'],$order,7,'status')['status']==='uncertain','orphaned sending state resolves to uncertain');check(!glob($orphanDir.'/*.csv'),'orphaned dispatch files discarded');
    $cancel=JPD_OD_Jobs::start($order,7,array('csv'));JPD_OD_Jobs::run($cancel['token'],$order,7,'generate','csv');$cancelDir=JPD_OD_Jobs::root().'/'.$cancel['token'];JPD_OD_Jobs::run($cancel['token'],$order,7,'cancel');check(!glob($cancelDir.'/*.csv'),'cancel removes ready files');
    $expired=JPD_OD_Jobs::start($order,7,array('csv'));$expiredDir=JPD_OD_Jobs::root().'/'.$expired['token'];$s=json_decode(file_get_contents($expiredDir.'/state.json'),true);$s['created']=time()-1801;JPD_OD_Jobs::write($expiredDir,$s);
    rejects(fn()=>JPD_OD_Jobs::run($expired['token'],$order,7,'generate','csv'),'expired operation refused');touch($expiredDir,time()-1801);JPD_OD_Jobs::cleanup();check(!is_dir($expiredDir),'expired idle operation cleaned opportunistically');
    $disabled=JPD_OD_Jobs::start($order,7,array('csv'));JPD_OD_Jobs::run($disabled['token'],$order,7,'generate','csv');$GLOBALS['wc']->mail->emails['JPD_OD_Email']->enabled='no';$n=WC_Email::$count;
    rejects(fn()=>JPD_OD_Jobs::run($disabled['token'],$order,7,'send'),'Woo email disabled setting respected');check(WC_Email::$count===$n,'disabled email never dispatched');
    echo "PASS: $checks backend checks\n";
} finally {JPD_OD_Jobs::cleanup(true);}
