<?php
defined( 'ABSPATH' ) || exit;
class JPD_OD_Email extends WC_Email {
    private $document_paths = array();
    public function __construct() {
        $this->id = 'jpd_order_documents';
        $this->title = 'JPD · Έγγραφα παραγγελίας';
        $this->description = 'Χειροκίνητη αποστολή συνοπτικού PDF και προαιρετικού CSV από εξουσιοδοτημένο πωλητή. Δεν αποστέλλεται αυτόματα όταν αλλάζει η κατάσταση παραγγελίας.';
        $this->customer_email = true;
        $this->manual = true;
        $this->placeholders = array( '{order_number}' => '', '{order_date}' => '' );
        parent::__construct();
    }
    public function get_default_subject() { return '{site_title} · Έγγραφα παραγγελίας #{order_number}'; }
    public function get_default_heading() { return 'Τα έγγραφα της παραγγελίας σας'; }
    public function init_form_fields() {
        $this->form_fields = array(
            'enabled' => array( 'title' => 'Ενεργοποίηση', 'type' => 'checkbox', 'label' => 'Επιτρέπεται η χειροκίνητη αποστολή εγγράφων', 'default' => 'yes' ),
            'subject' => array( 'title' => 'Θέμα', 'type' => 'text', 'default' => '', 'placeholder' => $this->get_default_subject(), 'desc_tip' => true, 'description' => 'Διαθέσιμα: {site_title}, {order_number}, {order_date}.' ),
            'heading' => array( 'title' => 'Επικεφαλίδα', 'type' => 'text', 'default' => '', 'placeholder' => $this->get_default_heading() ),
            'additional_content' => array( 'title' => 'Πρόσθετο κείμενο', 'type' => 'textarea', 'default' => '' ),
        );
        // This manual message always uses WooCommerce HTML branding.
        $this->email_type = 'html';
    }
    public function get_email_type() { return 'html'; }
    public function get_content_html() {
        ob_start();
        do_action( 'woocommerce_email_header', $this->get_heading(), $this ); ?>
        <p>Σας στέλνουμε συνημμένα τα έγγραφα της παραγγελίας<?php if ( $this->object instanceof WC_Order ) { echo ' #' . esc_html( $this->object->get_order_number() ); } ?>.</p>
        <p>Οι ποσότητες προέρχονται από την παραγγελία. Οι τιμές υπολογίστηκαν κατά τη δημιουργία των εγγράφων.</p>
        <p><a href="<?php echo esc_url( wc_get_endpoint_url( 'orders', '', wc_get_page_permalink( 'myaccount' ) ) ); ?>">Δείτε τις παραγγελίες σας</a></p>
        <?php if ( $this->get_additional_content() ) { echo wp_kses_post( wpautop( $this->get_additional_content() ) ); }
        do_action( 'woocommerce_email_footer', $this );
        return ob_get_clean();
    }
    public function get_content_plain() { return wp_strip_all_tags( $this->get_content_html() ); }
    public function get_attachments() {
        // Only documents selected and generated by this operation; no other plugin's attachment filter.
        return $this->document_paths;
    }
    public function send_documents( $order, $paths ) {
        if ( ! $this->is_enabled() ) { throw new RuntimeException( 'Το email «JPD · Έγγραφα παραγγελίας» είναι απενεργοποιημένο στις ρυθμίσεις WooCommerce.' ); }
        $this->object = $order;
        $this->recipient = $order->get_billing_email();
        $this->placeholders['{order_number}'] = $order->get_order_number();
        $date = $order->get_date_created();
        $this->placeholders['{order_date}'] = $date ? wc_format_datetime( $date ) : '';
        $this->document_paths = $paths;
        $this->setup_locale();
        try { return $this->send( $this->get_recipient(), $this->get_subject(), $this->get_content(), $this->get_headers(), $this->get_attachments() ); }
        finally { $this->document_paths = array(); $this->restore_locale(); }
    }
}
